# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'cine'
      MYSQL_ROOT_PASSWORD: 'films123'
    ports:
      - '3306:3306'


